INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is 3 + 5 = ?', '8', 1);
INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is 4 + 4 = ? ', '8', 2);
INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is 7 + 1 = ?', '8', 3);
INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is the 13th letter of the English alphabet?', 'm', 4);
INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is the 1st letter of the English alphabet?', 'a', 5);
INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is the 4th letter of the English alphabet?', 'd', 6);
INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is the 9th letter of the English alphabet?', 'i', 7);
INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is the 19th letter of the English alphabet?', 's', 8);
INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is the 15th letter of the English alphabet?', 'o', 9);
INSERT INTO map_questionandanswer (Question, Answer, QuestionNumber) VALUES ('What is the 14th letter of the English alphabet?', 'n', 10);
